#pragma config(Motor,  port2,           LeftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ClawUpper,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           ClawLower,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           Piston,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           Arm,           tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           RightWheel,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	const int CYCLE_RESET = 100;
	//___________________________________________________________________________________________________________________________________________


	int cycleCounter = 0;

	while(1)
	{
		cycleCounter += 1;

		if (cycleCounter > CYCLE_RESET)
		{
			cycleCounter = 0;
			//CLAW CODE
			if (vexRT [Btn6U])
			{
			   motor[ClawLower] += 1;
			}
			if (vexRT [Btn6D] )
			{
			   motor[ClawLower] -= 1;
			}

			if (vexRT [Btn5U])
			{
			   motor[ClawUpper] += 1;
			}
			if (vexRT [Btn5D] )
			{
			   motor[ClawUpper] -= 1;
			}
			
		}

			//WHEEL CODE
			motor[LeftWheel] = vexRT[Ch3];
			motor[RightWheel] = vexRT[Ch2];

			//ARM CODE
			if (vexRT [Btn5D])
			{
			   motor[Arm] = 127;
			}
			else if (vexRT [Btn5U] )
			{
			   motor[Arm] = -127;
			}
			else motor[Arm] = 0;

			// PISTON CODE
			if (vexRT [Btn8R])
			{
			   motor[Piston] = 127;
			}
			else if (vexRT [Btn8L] )
			{
			   motor[Piston] = -127;
			}
			else motor[Piston] = 0;


	}

}
