#pragma config(Motor,  port2,           LeftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ClawUpper,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           ClawLower,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           Arm,           tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           RightWheel,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	const int CYCLE_RESET = 100;
	const int MIN_CLAW_UPPER = -80;
	const int MAX_CLAW_UPPER = 15;
//	const int MIN_CLAW_LOWER = -15;
	const int MAX_CLAW_LOWER = 80;
	const int MIN_ARM = -120;
	const int MAX_ARM = 120;
	//___________________________________________________________________________________________________________________________________________


	int cycleCounter = 0;


	motor[ClawUpper] = MIN_CLAW_UPPER;
	motor[ClawLower] = MAX_CLAW_LOWER;

	while(1)
	{
		cycleCounter += 1;

		if (cycleCounter > CYCLE_RESET)
		{
			cycleCounter = 0;
			//CLAW CODE
			if (vexRT [Btn6U] && motor[ClawUpper] > MIN_CLAW_UPPER)
			{
			   motor[ClawUpper] -= 1;
			   motor[ClawLower] += 1;
			}
			if (vexRT [Btn6D] && motor[ClawUpper] < MAX_CLAW_UPPER)
			{
			   motor[ClawUpper] += 1;
			   motor[ClawLower] -= 1;
			}
			//ARM CODE
			if (vexRT [Btn5U] && motor[Arm] < MAX_ARM)
			{
			   motor[Arm] += 1;
			}
			if (vexRT [Btn5D] && motor[Arm] > MIN_ARM)
			{
			   motor[Arm] -= 1;
			}
			//WHEEL CODE
			motor[LeftWheel] = vexRT[Ch3];
			motor[RightWheel] = vexRT[Ch2];
		}






	}

}
